name: CI for Branches

on:
  push: 
    branches-ignore:
      - main
      - 'release/**'
      - 'hotfix/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: dummy build 
        run: echo 'Running build ... Success!'
