name: Deployment

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:

  deploy:
    name: Deploy to Prod
    runs-on: ubuntu-latest

    environment:
      name: PROD

    steps:
      - name: Deploy
      - run: echo 'Deploying ... Success!'
