name: Deployment to Production

on:

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  
  deploy:
    name: Deploy to Prod
    runs-on: ubuntu-latest

    environment:
      name: PROD

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Get the version
        id: get_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          
      - name: Search the package
        run: dotnet pack --configuration Release
      - name: Download Package
        uses: actions/upload-artifact@v2
        with: 
          name: ContosoPizza.${{ steps.get_version.outputs.release }}.nupkg
          path: ./bin/Release/ContosoPizza.1.0.0.nupkg
      - name: Deploy
        run: echo 'Deploying ContosoPizza.${{ steps.get_version.outputs.release }}.nupkg ... Success!'
      
      - uses: jules2689/adr-actions@main
        with:
          #adr-dir: 'contosopizza' # Optional. Directory in which ADRs are located. Defaults to contents of .adr-dir
          adr-tool-repo: 'https://github.com/david-iaggbs/global-crq.git' # Optional. ADR Tool Repo location 
          #debugadr-tool-version: '3.0.0' # Optional. Version of the Tools to use.
          #github-token: '${{ secrets.GITHUB_TOKEN }}' # Optional. Token with which to commit
          generate-toc-branches: "['main', 'master']" # Optional: JSON Array of Branch names as a string. specify which branches we should generate TOC on. Defaults to main/master. 

