name: Deployment to UAT

on:

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  
  deploy:
    name: Deploy to UAT
    runs-on: ubuntu-latest

    environment:
      name: UAT

    steps:
      - name: Get the version
        id: get_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: ContosoPizza.${{ steps.get_version.outputs.release }}.nupkg
      - name: Deploy
        run: echo 'Deploying ContosoPizza.${{ steps.get_version.outputs.release }}.nupkg ... Success!'
